//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 04:10:08 PM PDT 
//


package com.wb.nextgenlibrary.parser.appdata;

import java.util.ArrayList;
import java.util.List;
import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlSchemaType;
import com.wb.nextgenlibrary.parser.XmlType;


/**
 * <p>Java class for AppDataAcquireAsset-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppDataAcquireAsset-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ALID" type="{http://www.movielabs.com/schema/md/v2.4/md}AssetLogicalID-type"/&gt;
 *         &lt;element name="RequestType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FormatProfile" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PurchaseURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppDataAcquireAsset-type", propOrder = {
    "alid",
    "requestType",
    "formatProfile",
    "purchaseURL"
})
public class AppDataAcquireAssetType {

    @XmlElement(name = "ALID", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String alid;
    @XmlElement(name = "RequestType", required = true)
    protected String requestType;
    @XmlElement(name = "FormatProfile", required = true)
    protected String formatProfile;
    @XmlElement(name = "PurchaseURL")
    @XmlSchemaType(name = "anyURI")
    protected List<String> purchaseURL;

    /**
     * Gets the value of the alid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALID() {
        return alid;
    }

    /**
     * Sets the value of the alid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALID(String value) {
        this.alid = value;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestType(String value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the formatProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatProfile() {
        return formatProfile;
    }

    /**
     * Sets the value of the formatProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatProfile(String value) {
        this.formatProfile = value;
    }

    /**
     * Gets the value of the purchaseURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purchaseURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurchaseURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPurchaseURL() {
        if (purchaseURL == null) {
            purchaseURL = new ArrayList<String>();
        }
        return this.purchaseURL;
    }

}
