//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 04:10:08 PM PDT 
//


package com.wb.nextgenlibrary.parser.appdata;

import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlSchemaType;
import com.wb.nextgenlibrary.parser.XmlType;


/**
 * <p>Java class for AppDataTrackSelection-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppDataTrackSelection-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PresentationID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}PresentationID-type"/&gt;
 *         &lt;element name="SelectVideoTrack" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="SelectSubtitleTrack" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="SelectAudioTrack" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppDataTrackSelection-type", propOrder = {
    "presentationID",
    "selectVideoTrack",
    "selectSubtitleTrack",
    "selectAudioTrack"
})
public class AppDataTrackSelectionType {

    @XmlElement(name = "PresentationID", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String presentationID;
    @XmlElement(name = "SelectVideoTrack")
    protected boolean selectVideoTrack;
    @XmlElement(name = "SelectSubtitleTrack")
    protected boolean selectSubtitleTrack;
    @XmlElement(name = "SelectAudioTrack")
    protected boolean selectAudioTrack;

    /**
     * Gets the value of the presentationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationID() {
        return presentationID;
    }

    /**
     * Sets the value of the presentationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationID(String value) {
        this.presentationID = value;
    }

    /**
     * Gets the value of the selectVideoTrack property.
     * 
     */
    public boolean isSelectVideoTrack() {
        return selectVideoTrack;
    }

    /**
     * Sets the value of the selectVideoTrack property.
     * 
     */
    public void setSelectVideoTrack(boolean value) {
        this.selectVideoTrack = value;
    }

    /**
     * Gets the value of the selectSubtitleTrack property.
     * 
     */
    public boolean isSelectSubtitleTrack() {
        return selectSubtitleTrack;
    }

    /**
     * Sets the value of the selectSubtitleTrack property.
     * 
     */
    public void setSelectSubtitleTrack(boolean value) {
        this.selectSubtitleTrack = value;
    }

    /**
     * Gets the value of the selectAudioTrack property.
     * 
     */
    public boolean isSelectAudioTrack() {
        return selectAudioTrack;
    }

    /**
     * Sets the value of the selectAudioTrack property.
     * 
     */
    public void setSelectAudioTrack(boolean value) {
        this.selectAudioTrack = value;
    }

}
