//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 04:10:08 PM PDT 
//


package com.wb.nextgenlibrary.parser.appdata;

import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlSchemaType;
import com.wb.nextgenlibrary.parser.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for AppDataGallery-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppDataGallery-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GalleryID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}GalleryID-type"/&gt;
 *         &lt;element name="AutoNextSlideTime" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/&gt;
 *         &lt;element name="Loop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppDataGallery-type", propOrder = {
    "galleryID",
    "autoNextSlideTime",
    "loop"
})
public class AppDataGalleryType {

    @XmlElement(name = "GalleryID", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String galleryID;
    @XmlElement(name = "AutoNextSlideTime")
    protected Duration autoNextSlideTime;
    @XmlElement(name = "Loop")
    protected Boolean loop;

    /**
     * Gets the value of the galleryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGalleryID() {
        return galleryID;
    }

    /**
     * Sets the value of the galleryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGalleryID(String value) {
        this.galleryID = value;
    }

    /**
     * Gets the value of the autoNextSlideTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getAutoNextSlideTime() {
        return autoNextSlideTime;
    }

    /**
     * Sets the value of the autoNextSlideTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setAutoNextSlideTime(Duration value) {
        this.autoNextSlideTime = value;
    }

    /**
     * Gets the value of the loop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoop() {
        return loop;
    }

    /**
     * Sets the value of the loop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoop(Boolean value) {
        this.loop = value;
    }

}
