//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 04:10:08 PM PDT 
//


package com.wb.nextgenlibrary.parser.appdata;

import java.util.ArrayList;
import java.util.List;
import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlElements;
import com.wb.nextgenlibrary.parser.XmlType;


/**
 * <p>Java class for AppDataFeedSet-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppDataFeedSet-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="Generic" type="{http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata}AppDataFeedGeneric"/&gt;
 *         &lt;element name="Proprietary" type="{http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata}AppDataFeedProprietary-type"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppDataFeedSet-type", propOrder = {
    "genericOrProprietary"
})
public class AppDataFeedSetType {

    @XmlElements({
        @XmlElement(name = "Generic", type = AppDataFeedGeneric.class),
        @XmlElement(name = "Proprietary", type = AppDataFeedProprietaryType.class)
    })
    protected List<Object> genericOrProprietary;

    /**
     * Gets the value of the genericOrProprietary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericOrProprietary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericOrProprietary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppDataFeedGeneric }
     * {@link AppDataFeedProprietaryType }
     * 
     * 
     */
    public List<Object> getGenericOrProprietary() {
        if (genericOrProprietary == null) {
            genericOrProprietary = new ArrayList<Object>();
        }
        return this.genericOrProprietary;
    }

}
