//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 04:10:08 PM PDT 
//


package com.wb.nextgenlibrary.parser.appdata;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlAnyElement;
import com.wb.nextgenlibrary.parser.XmlAttribute;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlSchemaType;
import com.wb.nextgenlibrary.parser.XmlType;
import com.wb.nextgenlibrary.parser.XmlValue;
import com.wb.nextgenlibrary.parser.adapters.CollapsedStringAdapter;
import com.wb.nextgenlibrary.parser.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import com.wb.nextgenlibrary.parser.manifest.schema.v1_4.EventLocationType;
import com.wb.nextgenlibrary.parser.manifest.schema.v1_4.EventPeriodType;
import com.wb.nextgenlibrary.parser.manifest.schema.v1_4.OtherIDType;
import com.wb.nextgenlibrary.parser.manifest.schema.v1_4.TimecodeType;
import com.wb.nextgenlibrary.parser.manifest.schema.v1_4.TimedEventSequenceType;
import com.wb.nextgenlibrary.parser.manifest.schema.v1_4.TimedEventType;
import com.wb.nextgenlibrary.parser.md.schema.v2_3.BasicMetadataPeopleType;
import com.wb.nextgenlibrary.parser.md.schema.v2_3.MoneyType;


/**
 * <p>Java class for AppNVPair-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppNVPair-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Integer" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="Decimal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}duration"/&gt;
 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="URLPostfix" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}language"/&gt;
 *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *         &lt;element name="YearDateTime" type="{http://www.movielabs.com/schema/md/v2.4/md}YearDateOrTime-type"/&gt;
 *         &lt;element name="Money" type="{http://www.movielabs.com/schema/md/v2.4/md}Money-type"/&gt;
 *         &lt;element name="base64Binary" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="Location" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}EventLocation-type"/&gt;
 *         &lt;element name="Timecode" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}Timecode-type"/&gt;
 *         &lt;element name="Person" type="{http://www.movielabs.com/schema/md/v2.4/md}BasicMetadataPeople-type"/&gt;
 *         &lt;element name="TimePeriod" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}EventPeriod-type"/&gt;
 *         &lt;element name="TimedEvent" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}TimedEvent-type"/&gt;
 *         &lt;element name="PlayableSequenceID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}PlayableSequenceID-type"/&gt;
 *         &lt;element name="PresentationID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}PresentationID-type"/&gt;
 *         &lt;element name="ContentID" type="{http://www.movielabs.com/schema/md/v2.4/md}ContentID-type"/&gt;
 *         &lt;element name="PictureID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}PictureID-type"/&gt;
 *         &lt;element name="TextGroupID" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.movielabs.com/schema/manifest/v1.5/manifest&gt;TextGroupID-type"&gt;
 *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ALID" type="{http://www.movielabs.com/schema/md/v2.4/md}AssetLogicalID-type"/&gt;
 *         &lt;element name="EIDR" type="{http://www.movielabs.com/schema/md/v2.4/md}id-type"/&gt;
 *         &lt;element name="OtherID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}OtherID-type"/&gt;
 *         &lt;element name="ProductID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}OtherID-type"/&gt;
 *         &lt;element name="AdID"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[a-zA-Z1-9][a-zA-Z0-9]{10}[hHdD]?"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EANUPC"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Gallery" type="{http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata}AppDataGallery-type"/&gt;
 *         &lt;element name="LocationSet" type="{http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata}AppDataLocation-type"/&gt;
 *         &lt;element name="SelectTrack" type="{http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata}AppDataTrackSelection-type"/&gt;
 *         &lt;element name="DataFeedSet" type="{http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata}AppDataFeedSet-type"/&gt;
 *         &lt;element name="TimedEventSequence" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}TimedEventSequence-type"/&gt;
 *         &lt;element name="AcquireAsset" type="{http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata}AppDataAcquireAsset-type"/&gt;
 *         &lt;element name="KML" type="{http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata}AppDataKML-type"/&gt;
 *         &lt;any namespace='##other'/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="Name" use="required" type="{http://www.movielabs.com/schema/md/v2.4/md}id-type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppNVPair-type", propOrder = {
    "text",
    "integer",
    "decimal",
    "duration",
    "url",
    "urlPostfix",
    "language",
    "time",
    "yearDateTime",
    "money",
    "base64Binary",
    "location",
    "timecode",
    "person",
    "timePeriod",
    "timedEvent",
    "playableSequenceID",
    "presentationID",
    "contentID",
    "pictureID",
    "textGroupID",
    "alid",
    "eidr",
    "otherID",
    "productID",
    "adID",
    "eanupc",
    "gallery",
    "locationSet",
    "selectTrack",
    "dataFeedSet",
    "timedEventSequence",
    "acquireAsset",
    "kml",
    "any"
})
public class AppNVPairType {

    @XmlElement(name = "Text")
    protected String text;
    @XmlElement(name = "Integer")
    protected BigInteger integer;
    @XmlElement(name = "Decimal")
    protected BigDecimal decimal;
    @XmlElement(name = "Duration")
    protected Duration duration;
    @XmlElement(name = "URL")
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlElement(name = "URLPostfix")
    protected String urlPostfix;
    @XmlElement(name = "Language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String language;
    @XmlElement(name = "Time")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;
    @XmlElement(name = "YearDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String yearDateTime;
    @XmlElement(name = "Money")
    protected MoneyType money;
    protected byte[] base64Binary;
    @XmlElement(name = "Location")
    protected EventLocationType location;
    @XmlElement(name = "Timecode")
    protected TimecodeType timecode;
    @XmlElement(name = "Person")
    protected BasicMetadataPeopleType person;
    @XmlElement(name = "TimePeriod")
    protected EventPeriodType timePeriod;
    @XmlElement(name = "TimedEvent")
    protected TimedEventType timedEvent;
    @XmlElement(name = "PlayableSequenceID")
    @XmlSchemaType(name = "anyURI")
    protected String playableSequenceID;
    @XmlElement(name = "PresentationID")
    @XmlSchemaType(name = "anyURI")
    protected String presentationID;
    @XmlElement(name = "ContentID")
    @XmlSchemaType(name = "anyURI")
    protected String contentID;
    @XmlElement(name = "PictureID")
    @XmlSchemaType(name = "anyURI")
    protected String pictureID;
    @XmlElement(name = "TextGroupID")
    protected List<TextGroupID> textGroupID;
    @XmlElement(name = "ALID")
    @XmlSchemaType(name = "anyURI")
    protected String alid;
    @XmlElement(name = "EIDR")
    @XmlSchemaType(name = "anyURI")
    protected String eidr;
    @XmlElement(name = "OtherID")
    protected OtherIDType otherID;
    @XmlElement(name = "ProductID")
    protected OtherIDType productID;
    @XmlElement(name = "AdID")
    protected String adID;
    @XmlElement(name = "EANUPC")
    protected AppNVPairType.EANUPC eanupc;
    @XmlElement(name = "Gallery")
    protected AppDataGalleryType gallery;
    @XmlElement(name = "LocationSet")
    protected AppDataLocationType locationSet;
    @XmlElement(name = "SelectTrack")
    protected AppDataTrackSelectionType selectTrack;
    @XmlElement(name = "DataFeedSet")
    protected AppDataFeedSetType dataFeedSet;
    @XmlElement(name = "TimedEventSequence")
    protected TimedEventSequenceType timedEventSequence;
    @XmlElement(name = "AcquireAsset")
    protected AppDataAcquireAssetType acquireAsset;
    @XmlElement(name = "KML")
    protected AppDataKMLType kml;
    @XmlElement(name = "ExperienceID")
    protected String experienceId;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Gets the value of the experienceId.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExperienceID() {
        return experienceId;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Sets the value of the experiendId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExperienceID(String value) {
        this.experienceId = value;
    }

    /**
     * Gets the value of the integer property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getInteger() {
        return integer;
    }

    /**
     * Sets the value of the integer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInteger(BigInteger value) {
        this.integer = value;
    }

    /**
     * Gets the value of the decimal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDecimal() {
        return decimal;
    }

    /**
     * Sets the value of the decimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDecimal(BigDecimal value) {
        this.decimal = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the urlPostfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLPostfix() {
        return urlPostfix;
    }

    /**
     * Sets the value of the urlPostfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLPostfix(String value) {
        this.urlPostfix = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the yearDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearDateTime() {
        return yearDateTime;
    }

    /**
     * Sets the value of the yearDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearDateTime(String value) {
        this.yearDateTime = value;
    }

    /**
     * Gets the value of the money property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyType }
     *     
     */
    public MoneyType getMoney() {
        return money;
    }

    /**
     * Sets the value of the money property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyType }
     *     
     */
    public void setMoney(MoneyType value) {
        this.money = value;
    }

    /**
     * Gets the value of the base64Binary property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBase64Binary() {
        return base64Binary;
    }

    /**
     * Sets the value of the base64Binary property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBase64Binary(byte[] value) {
        this.base64Binary = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link EventLocationType }
     *     
     */
    public EventLocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventLocationType }
     *     
     */
    public void setLocation(EventLocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the timecode property.
     * 
     * @return
     *     possible object is
     *     {@link TimecodeType }
     *     
     */
    public TimecodeType getTimecode() {
        return timecode;
    }

    /**
     * Sets the value of the timecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimecodeType }
     *     
     */
    public void setTimecode(TimecodeType value) {
        this.timecode = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link BasicMetadataPeopleType }
     *     
     */
    public BasicMetadataPeopleType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicMetadataPeopleType }
     *     
     */
    public void setPerson(BasicMetadataPeopleType value) {
        this.person = value;
    }

    /**
     * Gets the value of the timePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link EventPeriodType }
     *     
     */
    public EventPeriodType getTimePeriod() {
        return timePeriod;
    }

    /**
     * Sets the value of the timePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventPeriodType }
     *     
     */
    public void setTimePeriod(EventPeriodType value) {
        this.timePeriod = value;
    }

    /**
     * Gets the value of the timedEvent property.
     * 
     * @return
     *     possible object is
     *     {@link TimedEventType }
     *     
     */
    public TimedEventType getTimedEvent() {
        return timedEvent;
    }

    /**
     * Sets the value of the timedEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimedEventType }
     *     
     */
    public void setTimedEvent(TimedEventType value) {
        this.timedEvent = value;
    }

    /**
     * Gets the value of the playableSequenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayableSequenceID() {
        return playableSequenceID;
    }

    /**
     * Sets the value of the playableSequenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayableSequenceID(String value) {
        this.playableSequenceID = value;
    }

    /**
     * Gets the value of the presentationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationID() {
        return presentationID;
    }

    /**
     * Sets the value of the presentationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationID(String value) {
        this.presentationID = value;
    }

    /**
     * Gets the value of the contentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentID() {
        return contentID;
    }

    /**
     * Sets the value of the contentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentID(String value) {
        this.contentID = value;
    }

    /**
     * Gets the value of the pictureID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPictureID() {
        return pictureID;
    }

    /**
     * Sets the value of the pictureID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPictureID(String value) {
        this.pictureID = value;
    }

    /**
     * Gets the value of the textGroupID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textGroupID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextGroupID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextGroupID }
     * 
     * 
     */
    public List<TextGroupID> getTextGroupID() {
        if (textGroupID == null) {
            textGroupID = new ArrayList<TextGroupID>();
        }
        return this.textGroupID;
    }

    /**
     * Gets the value of the alid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALID() {
        return alid;
    }

    /**
     * Sets the value of the alid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALID(String value) {
        this.alid = value;
    }

    /**
     * Gets the value of the eidr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEIDR() {
        return eidr;
    }

    /**
     * Sets the value of the eidr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEIDR(String value) {
        this.eidr = value;
    }

    /**
     * Gets the value of the otherID property.
     * 
     * @return
     *     possible object is
     *     {@link OtherIDType }
     *     
     */
    public OtherIDType getOtherID() {
        return otherID;
    }

    /**
     * Sets the value of the otherID property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherIDType }
     *     
     */
    public void setOtherID(OtherIDType value) {
        this.otherID = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link OtherIDType }
     *     
     */
    public OtherIDType getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherIDType }
     *     
     */
    public void setProductID(OtherIDType value) {
        this.productID = value;
    }

    /**
     * Gets the value of the adID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdID() {
        return adID;
    }

    /**
     * Sets the value of the adID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdID(String value) {
        this.adID = value;
    }

    /**
     * Gets the value of the eanupc property.
     * 
     * @return
     *     possible object is
     *     {@link EANUPC }
     *     
     */
    public EANUPC getEANUPC() {
        return eanupc;
    }

    /**
     * Sets the value of the eanupc property.
     * 
     * @param value
     *     allowed object is
     *     {@link EANUPC }
     *     
     */
    public void setEANUPC(EANUPC value) {
        this.eanupc = value;
    }

    /**
     * Gets the value of the gallery property.
     * 
     * @return
     *     possible object is
     *     {@link AppDataGalleryType }
     *     
     */
    public AppDataGalleryType getGallery() {
        return gallery;
    }

    /**
     * Sets the value of the gallery property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppDataGalleryType }
     *     
     */
    public void setGallery(AppDataGalleryType value) {
        this.gallery = value;
    }

    /**
     * Gets the value of the locationSet property.
     * 
     * @return
     *     possible object is
     *     {@link AppDataLocationType }
     *     
     */
    public AppDataLocationType getLocationSet() {
        return locationSet;
    }

    /**
     * Sets the value of the locationSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppDataLocationType }
     *     
     */
    public void setLocationSet(AppDataLocationType value) {
        this.locationSet = value;
    }

    /**
     * Gets the value of the selectTrack property.
     * 
     * @return
     *     possible object is
     *     {@link AppDataTrackSelectionType }
     *     
     */
    public AppDataTrackSelectionType getSelectTrack() {
        return selectTrack;
    }

    /**
     * Sets the value of the selectTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppDataTrackSelectionType }
     *     
     */
    public void setSelectTrack(AppDataTrackSelectionType value) {
        this.selectTrack = value;
    }

    /**
     * Gets the value of the dataFeedSet property.
     * 
     * @return
     *     possible object is
     *     {@link AppDataFeedSetType }
     *     
     */
    public AppDataFeedSetType getDataFeedSet() {
        return dataFeedSet;
    }

    /**
     * Sets the value of the dataFeedSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppDataFeedSetType }
     *     
     */
    public void setDataFeedSet(AppDataFeedSetType value) {
        this.dataFeedSet = value;
    }

    /**
     * Gets the value of the timedEventSequence property.
     * 
     * @return
     *     possible object is
     *     {@link TimedEventSequenceType }
     *     
     */
    public TimedEventSequenceType getTimedEventSequence() {
        return timedEventSequence;
    }

    /**
     * Sets the value of the timedEventSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimedEventSequenceType }
     *     
     */
    public void setTimedEventSequence(TimedEventSequenceType value) {
        this.timedEventSequence = value;
    }

    /**
     * Gets the value of the acquireAsset property.
     * 
     * @return
     *     possible object is
     *     {@link AppDataAcquireAssetType }
     *     
     */
    public AppDataAcquireAssetType getAcquireAsset() {
        return acquireAsset;
    }

    /**
     * Sets the value of the acquireAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppDataAcquireAssetType }
     *     
     */
    public void setAcquireAsset(AppDataAcquireAssetType value) {
        this.acquireAsset = value;
    }

    /**
     * Gets the value of the kml property.
     * 
     * @return
     *     possible object is
     *     {@link AppDataKMLType }
     *     
     */
    public AppDataKMLType getKML() {
        return kml;
    }

    /**
     * Sets the value of the kml property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppDataKMLType }
     *     
     */
    public void setKML(AppDataKMLType value) {
        this.kml = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class EANUPC {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "format")
        protected String format;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.movielabs.com/schema/manifest/v1.5/manifest&gt;TextGroupID-type"&gt;
     *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TextGroupID {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "index")
        protected BigInteger index;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the index property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIndex() {
            return index;
        }

        /**
         * Sets the value of the index property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIndex(BigInteger value) {
            this.index = value;
        }

    }

}
