//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 04:10:08 PM PDT 
//


package com.wb.nextgenlibrary.parser.appdata;

import com.wb.nextgenlibrary.parser.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.movielabs.schema.md.manifestdata.v1_0.manifestdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ManifestAppDataSet_QNAME = new QName("http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata", "ManifestAppDataSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.movielabs.schema.md.manifestdata.v1_0.manifestdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AppNVPairType }
     * 
     */
    public AppNVPairType createAppNVPairType() {
        return new AppNVPairType();
    }

    /**
     * Create an instance of {@link AppDataLocationType }
     * 
     */
    public AppDataLocationType createAppDataLocationType() {
        return new AppDataLocationType();
    }

    /**
     * Create an instance of {@link ManifestAppDataSetType }
     * 
     */
    public ManifestAppDataSetType createManifestAppDataSetType() {
        return new ManifestAppDataSetType();
    }

    /**
     * Create an instance of {@link AppDataAcquireAssetType }
     * 
     */
    public AppDataAcquireAssetType createAppDataAcquireAssetType() {
        return new AppDataAcquireAssetType();
    }

    /**
     * Create an instance of {@link AppDataFeedGeneric }
     * 
     */
    public AppDataFeedGeneric createAppDataFeedGeneric() {
        return new AppDataFeedGeneric();
    }

    /**
     * Create an instance of {@link AppDataFeedProprietaryType }
     * 
     */
    public AppDataFeedProprietaryType createAppDataFeedProprietaryType() {
        return new AppDataFeedProprietaryType();
    }

    /**
     * Create an instance of {@link AppDataFeedSetType }
     * 
     */
    public AppDataFeedSetType createAppDataFeedSetType() {
        return new AppDataFeedSetType();
    }

    /**
     * Create an instance of {@link AppDataTrackSelectionType }
     * 
     */
    public AppDataTrackSelectionType createAppDataTrackSelectionType() {
        return new AppDataTrackSelectionType();
    }

    /**
     * Create an instance of {@link AppDataSpecialBehaviorType }
     * 
     */
    public AppDataSpecialBehaviorType createAppDataSpecialBehaviorType() {
        return new AppDataSpecialBehaviorType();
    }

    /**
     * Create an instance of {@link AppDataGalleryType }
     * 
     */
    public AppDataGalleryType createAppDataGalleryType() {
        return new AppDataGalleryType();
    }

    /**
     * Create an instance of {@link AppDataKMLType }
     * 
     */
    public AppDataKMLType createAppDataKMLType() {
        return new AppDataKMLType();
    }

    /**
     * Create an instance of {@link TimelineStyleType }
     * 
     */
    public TimelineStyleType createTimelineStyleType() {
        return new TimelineStyleType();
    }

    /**
     * Create an instance of {@link AppDataType }
     * 
     */
    public AppDataType createAppDataType() {
        return new AppDataType();
    }

    /**
     * Create an instance of {@link AppNVPairType.TextGroupID }
     * 
     */
    public AppNVPairType.TextGroupID createAppNVPairTypeTextGroupID() {
        return new AppNVPairType.TextGroupID();
    }

    /**
     * Create an instance of {@link AppNVPairType.EANUPC }
     * 
     */
    public AppNVPairType.EANUPC createAppNVPairTypeEANUPC() {
        return new AppNVPairType.EANUPC();
    }

    /**
     * Create an instance of {@link AppDataLocationType.Location }
     * 
     */
    public AppDataLocationType.Location createAppDataLocationTypeLocation() {
        return new AppDataLocationType.Location();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManifestAppDataSetType }{@code >}}
     * 

    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata", name = "ManifestAppDataSet")
    public JAXBElement<ManifestAppDataSetType> createManifestAppDataSet(ManifestAppDataSetType value) {
        return new JAXBElement<ManifestAppDataSetType>(_ManifestAppDataSet_QNAME, ManifestAppDataSetType.class, null, value);
    }*/

}
