//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 04:10:08 PM PDT 
//

@com.wb.nextgenlibrary.parser.XmlSchema(namespace = "http://www.movielabs.com/schema/md/manifestdata/v1.0/manifestdata", elementFormDefault = com.wb.nextgenlibrary.parser.XmlNsForm.QUALIFIED)
package com.wb.nextgenlibrary.parser.appdata;
