//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgenlibrary.parser.manifest.schema.v1_4;

import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlAttribute;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlType;
import com.wb.nextgenlibrary.parser.md.schema.v2_3.DigitalAssetImageDataType;


/**
 * <p>Java class for InventoryImage-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InventoryImage-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetImageData-type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ContainerReference" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ContainerReference-type" minOccurs="0"/&gt;
 *         &lt;element name="VideoFrameTimecode" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.movielabs.com/schema/manifest/v1.4/manifest&gt;Timecode-type"&gt;
 *                 &lt;attribute name="VideoTrackID" use="required" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}VideoTrackID-type" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ImageID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ImageID-type" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InventoryImage-type", propOrder = {
    "containerReference",
    "videoFrameTimecode"
})
public class InventoryImageType
    extends DigitalAssetImageDataType
{

    @XmlElement(name = "ContainerReference")
    protected ContainerReferenceType containerReference;
    @XmlElement(name = "VideoFrameTimecode")
    protected InventoryImageType.VideoFrameTimecode videoFrameTimecode;
    @XmlAttribute(name = "ImageID")
    protected String imageID;

    /**
     * Gets the value of the containerReference property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerReferenceType }
     *     
     */
    public ContainerReferenceType getContainerReference() {
        return containerReference;
    }

    /**
     * Sets the value of the containerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerReferenceType }
     *     
     */
    public void setContainerReference(ContainerReferenceType value) {
        this.containerReference = value;
    }

    /**
     * Gets the value of the videoFrameTimecode property.
     * 
     * @return
     *     possible object is
     *     {@link VideoFrameTimecode }
     *     
     */
    public VideoFrameTimecode getVideoFrameTimecode() {
        return videoFrameTimecode;
    }

    /**
     * Sets the value of the videoFrameTimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoFrameTimecode }
     *     
     */
    public void setVideoFrameTimecode(VideoFrameTimecode value) {
        this.videoFrameTimecode = value;
    }

    /**
     * Gets the value of the imageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageID() {
        return imageID;
    }

    /**
     * Sets the value of the imageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageID(String value) {
        this.imageID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.movielabs.com/schema/manifest/v1.4/manifest&gt;Timecode-type"&gt;
     *       &lt;attribute name="VideoTrackID" use="required" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}VideoTrackID-type" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class VideoFrameTimecode
        extends TimecodeType
    {

        @XmlAttribute(name = "VideoTrackID", required = true)
        protected String videoTrackID;

        /**
         * Gets the value of the videoTrackID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVideoTrackID() {
            return videoTrackID;
        }

        /**
         * Sets the value of the videoTrackID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVideoTrackID(String value) {
            this.videoTrackID = value;
        }

    }

}
