//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//

@com.wb.nextgenlibrary.parser.XmlSchema(namespace = "http://www.movielabs.com/schema/manifest/v1.4/manifest", elementFormDefault = com.wb.nextgenlibrary.parser.XmlNsForm.QUALIFIED)
package com.wb.nextgenlibrary.parser.manifest.schema.v1_4;
