//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 03:29:52 PM PDT 
//


package com.wb.nextgenlibrary.parser.cpestyle;

import java.util.ArrayList;
import java.util.List;
import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlAttribute;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlType;


/**
 * <p>Java class for Background-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Background-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Color" type="{http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle}ColorHex-type" minOccurs="0"/&gt;
 *         &lt;element name="Image" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle}BackgroundImage-type"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Video" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle}BackgroundVideo-type"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AudioLoop" type="{http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle}BackgroundAudio-type" minOccurs="0"/&gt;
 *         &lt;element name="Adaptation" type="{http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle}BackgroundAdaptation-type" minOccurs="0"/&gt;
 *         &lt;element name="OverlayArea" type="{http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle}BackgroundOverlayArea-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="looping" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Background-type", propOrder = {
    "color",
    "image",
    "video",
    "audioLoop",
    "adaptation",
    "overlayArea"
})
public class BackgroundType {

    @XmlElement(name = "Color")
    protected String color;
    @XmlElement(name = "Image")
    protected BackgroundType.Image image;
    @XmlElement(name = "Video")
    protected BackgroundType.Video video;
    @XmlElement(name = "AudioLoop")
    protected BackgroundAudioType audioLoop;
    @XmlElement(name = "Adaptation")
    protected BackgroundAdaptationType adaptation;
    @XmlElement(name = "OverlayArea")
    protected List<BackgroundOverlayAreaType> overlayArea;
    @XmlAttribute(name = "looping")
    protected Boolean looping;

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundType.Image }
     *     
     */
    public BackgroundType.Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundType.Image }
     *     
     */
    public void setImage(BackgroundType.Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the video property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundType.Video }
     *     
     */
    public BackgroundType.Video getVideo() {
        return video;
    }

    /**
     * Sets the value of the video property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundType.Video }
     *     
     */
    public void setVideo(BackgroundType.Video value) {
        this.video = value;
    }

    /**
     * Gets the value of the audioLoop property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundAudioType }
     *     
     */
    public BackgroundAudioType getAudioLoop() {
        return audioLoop;
    }

    /**
     * Sets the value of the audioLoop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundAudioType }
     *     
     */
    public void setAudioLoop(BackgroundAudioType value) {
        this.audioLoop = value;
    }

    /**
     * Gets the value of the adaptation property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundAdaptationType }
     *     
     */
    public BackgroundAdaptationType getAdaptation() {
        return adaptation;
    }

    /**
     * Sets the value of the adaptation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundAdaptationType }
     *     
     */
    public void setAdaptation(BackgroundAdaptationType value) {
        this.adaptation = value;
    }

    /**
     * Gets the value of the overlayArea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the overlayArea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverlayArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BackgroundOverlayAreaType }
     * 
     * 
     */
    public List<BackgroundOverlayAreaType> getOverlayArea() {
        if (overlayArea == null) {
            overlayArea = new ArrayList<BackgroundOverlayAreaType>();
        }
        return this.overlayArea;
    }

    /**
     * Gets the value of the looping property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLooping() {
        return looping;
    }

    /**
     * Sets the value of the looping property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLooping(Boolean value) {
        this.looping = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle}BackgroundImage-type"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Image
        extends BackgroundImageType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle}BackgroundVideo-type"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Video
        extends BackgroundVideoType
    {


    }

}
