//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 03:29:52 PM PDT 
//


package com.wb.nextgenlibrary.parser.cpestyle;

import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlSchemaType;
import com.wb.nextgenlibrary.parser.XmlSeeAlso;
import com.wb.nextgenlibrary.parser.XmlType;
import com.wb.nextgenlibrary.parser.manifest.schema.v1_4.TimecodeType;


/**
 * <p>Java class for BackgroundVideo-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BackgroundVideo-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Inherit" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="PresentationID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}PresentationID-type"/&gt;
 *         &lt;element name="PlayableSequenceID" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}PlayableSequenceID-type"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackgroundVideo-type", propOrder = {
    "inherit",
    "presentationID",
    "playableSequenceID"
})
@XmlSeeAlso({
    com.wb.nextgenlibrary.parser.cpestyle.BackgroundType.Video.class
})
public class BackgroundVideoType {

    @XmlElement(name = "Inherit")
    protected Boolean inherit;
    @XmlElement(name = "PresentationID")
    @XmlSchemaType(name = "anyURI")
    protected String presentationID;
    @XmlElement(name = "PlayableSequenceID")
    @XmlSchemaType(name = "anyURI")
    protected String playableSequenceID;
    @XmlElement(name = "LoopTimecode")
    protected TimecodeType loopTimecode;

    /**
     * Gets the value of the inherit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInherit() {
        return inherit;
    }

    /**
     * Sets the value of the inherit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInherit(Boolean value) {
        this.inherit = value;
    }

    /**
     * Gets the value of the presentationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationID() {
        return presentationID;
    }

    /**
     * Sets the value of the presentationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationID(String value) {
        this.presentationID = value;
    }

    /**
     * Gets the value of the playableSequenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayableSequenceID() {
        return playableSequenceID;
    }

    /**
     * Sets the value of the playableSequenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayableSequenceID(String value) {
        this.playableSequenceID = value;
    }

    /**
     * Gets the value of the loopTimecode property.
     *
     * @return
     *     possible object is
     *     {@link TimecodeType }
     *
     */
    public TimecodeType getLoopTimecode() {
        return loopTimecode;
    }

    /**
     * Sets the value of the loopTimecode property.
     *
     * @param value
     *     allowed object is
     *     {@link TimecodeType }
     *
     */
    public void setLoopTimecode(TimecodeType value) {
        this.loopTimecode = value;
    }

}
