//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 03:29:52 PM PDT 
//


package com.wb.nextgenlibrary.parser.cpestyle;

import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlSchemaType;
import com.wb.nextgenlibrary.parser.XmlSeeAlso;
import com.wb.nextgenlibrary.parser.XmlType;


/**
 * <p>Java class for ButtonImages-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ButtonImages-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BaseImage" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}ImageID-type"/&gt;
 *         &lt;element name="HighlightImage" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}ImageID-type"/&gt;
 *         &lt;element name="DefocusImage" type="{http://www.movielabs.com/schema/manifest/v1.5/manifest}ImageID-type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ButtonImages-type", propOrder = {
    "baseImage",
    "highlightImage",
    "defocusImage"
})
@XmlSeeAlso({
    com.wb.nextgenlibrary.parser.cpestyle.ButtonType.Default.class,
    com.wb.nextgenlibrary.parser.cpestyle.ButtonType.Localized.class
})
public class ButtonImagesType {

    @XmlElement(name = "BaseImage", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String baseImage;
    @XmlElement(name = "HighlightImage", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String highlightImage;
    @XmlElement(name = "DefocusImage", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String defocusImage;

    /**
     * Gets the value of the baseImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseImage() {
        return baseImage;
    }

    /**
     * Sets the value of the baseImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseImage(String value) {
        this.baseImage = value;
    }

    /**
     * Gets the value of the highlightImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighlightImage() {
        return highlightImage;
    }

    /**
     * Sets the value of the highlightImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighlightImage(String value) {
        this.highlightImage = value;
    }

    /**
     * Gets the value of the defocusImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefocusImage() {
        return defocusImage;
    }

    /**
     * Sets the value of the defocusImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefocusImage(String value) {
        this.defocusImage = value;
    }

}
