//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 03:29:52 PM PDT 
//


package com.wb.nextgenlibrary.parser.cpestyle;

import java.math.BigInteger;
import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlAttribute;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlSchemaType;
import com.wb.nextgenlibrary.parser.XmlType;


/**
 * <p>Java class for CompatibilityResolution-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompatibilityResolution-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WidthPixels" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="HeightPixels" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element name="SafeWidthPixels" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *           &lt;element name="SafeHeightPixels" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *           &lt;element name="SafePixelsFromLeft" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *           &lt;element name="SafePixelsFromBottom" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="rotate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="crop" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompatibilityResolution-type", propOrder = {
    "widthPixels",
    "heightPixels",
    "safeWidthPixels",
    "safeHeightPixels",
    "safePixelsFromLeft",
    "safePixelsFromBottom"
})
public class CompatibilityResolutionType {

    @XmlElement(name = "WidthPixels", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger widthPixels;
    @XmlElement(name = "HeightPixels", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger heightPixels;
    @XmlElement(name = "SafeWidthPixels")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger safeWidthPixels;
    @XmlElement(name = "SafeHeightPixels")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger safeHeightPixels;
    @XmlElement(name = "SafePixelsFromLeft")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger safePixelsFromLeft;
    @XmlElement(name = "SafePixelsFromBottom")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger safePixelsFromBottom;
    @XmlAttribute(name = "rotate", required = true)
    protected boolean rotate;
    @XmlAttribute(name = "crop", required = true)
    protected boolean crop;

    /**
     * Gets the value of the widthPixels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWidthPixels() {
        return widthPixels;
    }

    /**
     * Sets the value of the widthPixels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWidthPixels(BigInteger value) {
        this.widthPixels = value;
    }

    /**
     * Gets the value of the heightPixels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeightPixels() {
        return heightPixels;
    }

    /**
     * Sets the value of the heightPixels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeightPixels(BigInteger value) {
        this.heightPixels = value;
    }

    /**
     * Gets the value of the safeWidthPixels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSafeWidthPixels() {
        return safeWidthPixels;
    }

    /**
     * Sets the value of the safeWidthPixels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSafeWidthPixels(BigInteger value) {
        this.safeWidthPixels = value;
    }

    /**
     * Gets the value of the safeHeightPixels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSafeHeightPixels() {
        return safeHeightPixels;
    }

    /**
     * Sets the value of the safeHeightPixels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSafeHeightPixels(BigInteger value) {
        this.safeHeightPixels = value;
    }

    /**
     * Gets the value of the safePixelsFromLeft property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSafePixelsFromLeft() {
        return safePixelsFromLeft;
    }

    /**
     * Sets the value of the safePixelsFromLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSafePixelsFromLeft(BigInteger value) {
        this.safePixelsFromLeft = value;
    }

    /**
     * Gets the value of the safePixelsFromBottom property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSafePixelsFromBottom() {
        return safePixelsFromBottom;
    }

    /**
     * Sets the value of the safePixelsFromBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSafePixelsFromBottom(BigInteger value) {
        this.safePixelsFromBottom = value;
    }

    /**
     * Gets the value of the rotate property.
     * 
     */
    public boolean isRotate() {
        return rotate;
    }

    /**
     * Sets the value of the rotate property.
     * 
     */
    public void setRotate(boolean value) {
        this.rotate = value;
    }

    /**
     * Gets the value of the crop property.
     * 
     */
    public boolean isCrop() {
        return crop;
    }

    /**
     * Sets the value of the crop property.
     * 
     */
    public void setCrop(boolean value) {
        this.crop = value;
    }

}
