//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 03:29:52 PM PDT 
//


package com.wb.nextgenlibrary.parser.cpestyle;

import com.wb.nextgenlibrary.parser.XmlAccessType;
import com.wb.nextgenlibrary.parser.XmlAccessorType;
import com.wb.nextgenlibrary.parser.XmlElement;
import com.wb.nextgenlibrary.parser.XmlType;


/**
 * <p>Java class for Fonts-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fonts-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FontGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CSSFontFamily" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CSS3FontProperties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fonts-type", propOrder = {
    "fontGroup",
    "cssFontFamily",
    "css3FontProperties"
})
public class FontsType {

    @XmlElement(name = "FontGroup", required = true)
    protected String fontGroup;
    @XmlElement(name = "CSSFontFamily")
    protected String cssFontFamily;
    @XmlElement(name = "CSS3FontProperties")
    protected String css3FontProperties;

    /**
     * Gets the value of the fontGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontGroup() {
        return fontGroup;
    }

    /**
     * Sets the value of the fontGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontGroup(String value) {
        this.fontGroup = value;
    }

    /**
     * Gets the value of the cssFontFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSSFontFamily() {
        return cssFontFamily;
    }

    /**
     * Sets the value of the cssFontFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSSFontFamily(String value) {
        this.cssFontFamily = value;
    }

    /**
     * Gets the value of the css3FontProperties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSS3FontProperties() {
        return css3FontProperties;
    }

    /**
     * Sets the value of the css3FontProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSS3FontProperties(String value) {
        this.css3FontProperties = value;
    }

}
