//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 03:29:52 PM PDT 
//


package com.wb.nextgenlibrary.parser.cpestyle;

import com.wb.nextgenlibrary.parser.XmlElementDecl;
import com.wb.nextgenlibrary.parser.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wb.nextgenlibrary.parser.cpestyle package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CPEStyleSet_QNAME = new QName("http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle", "CPEStyleSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wb.nextgenlibrary.parser.cpestyle
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExperienceMenuMapType }
     * 
     */
    public ExperienceMenuMapType createExperienceMenuMapType() {
        return new ExperienceMenuMapType();
    }

    /**
     * Create an instance of {@link ButtonType }
     * 
     */
    public ButtonType createButtonType() {
        return new ButtonType();
    }

    /**
     * Create an instance of {@link BackgroundType }
     * 
     */
    public BackgroundType createBackgroundType() {
        return new BackgroundType();
    }

    /**
     * Create an instance of {@link BackgroundImageType }
     * 
     */
    public BackgroundImageType createBackgroundImageType() {
        return new BackgroundImageType();
    }

    /**
     * Create an instance of {@link NodeStyleType }
     * 
     */
    public NodeStyleType createNodeStyleType() {
        return new NodeStyleType();
    }

    /**
     * Create an instance of {@link CPEStyleSetType }
     * 
     */
    public CPEStyleSetType createCPEStyleSetType() {
        return new CPEStyleSetType();
    }

    /**
     * Create an instance of {@link ImageSubAreaType }
     * 
     */
    public ImageSubAreaType createImageSubAreaType() {
        return new ImageSubAreaType();
    }

    /**
     * Create an instance of {@link BackgroundVideoType }
     * 
     */
    public BackgroundVideoType createBackgroundVideoType() {
        return new BackgroundVideoType();
    }

    /**
     * Create an instance of {@link BackgroundAudioType }
     * 
     */
    public BackgroundAudioType createBackgroundAudioType() {
        return new BackgroundAudioType();
    }

    /**
     * Create an instance of {@link BackgroundAdaptationType }
     * 
     */
    public BackgroundAdaptationType createBackgroundAdaptationType() {
        return new BackgroundAdaptationType();
    }

    /**
     * Create an instance of {@link BackgroundOverlayAreaType }
     * 
     */
    public BackgroundOverlayAreaType createBackgroundOverlayAreaType() {
        return new BackgroundOverlayAreaType();
    }

    /**
     * Create an instance of {@link ColorPaletteInstanceType }
     * 
     */
    public ColorPaletteInstanceType createColorPaletteInstanceType() {
        return new ColorPaletteInstanceType();
    }

    /**
     * Create an instance of {@link ColorPaletteType }
     * 
     */
    public ColorPaletteType createColorPaletteType() {
        return new ColorPaletteType();
    }

    /**
     * Create an instance of {@link ThemeType }
     * 
     */
    public ThemeType createThemeType() {
        return new ThemeType();
    }

    /**
     * Create an instance of {@link ButtonImagesType }
     * 
     */
    public ButtonImagesType createButtonImagesType() {
        return new ButtonImagesType();
    }

    /**
     * Create an instance of {@link ButtonSetType }
     * 
     */
    public ButtonSetType createButtonSetType() {
        return new ButtonSetType();
    }

    /**
     * Create an instance of {@link FontsType }
     * 
     */
    public FontsType createFontsType() {
        return new FontsType();
    }

    /**
     * Create an instance of {@link CompatibilityDeviceType }
     * 
     */
    public CompatibilityDeviceType createCompatibilityDeviceType() {
        return new CompatibilityDeviceType();
    }

    /**
     * Create an instance of {@link CompatibilityResolutionType }
     * 
     */
    public CompatibilityResolutionType createCompatibilityResolutionType() {
        return new CompatibilityResolutionType();
    }

    /**
     * Create an instance of {@link NodeStyleRefType }
     * 
     */
    public NodeStyleRefType createNodeStyleRefType() {
        return new NodeStyleRefType();
    }

    /**
     * Create an instance of {@link ExperienceMenuMapType.NodeStyleRef }
     * 
     */
    public ExperienceMenuMapType.NodeStyleRef createExperienceMenuMapTypeNodeStyleRef() {
        return new ExperienceMenuMapType.NodeStyleRef();
    }

    /**
     * Create an instance of {@link ButtonType.Default }
     * 
     */
    public ButtonType.Default createButtonTypeDefault() {
        return new ButtonType.Default();
    }

    /**
     * Create an instance of {@link ButtonType.Localized }
     * 
     */
    public ButtonType.Localized createButtonTypeLocalized() {
        return new ButtonType.Localized();
    }

    /**
     * Create an instance of {@link BackgroundType.Image }
     * 
     */
    public BackgroundType.Image createBackgroundTypeImage() {
        return new BackgroundType.Image();
    }

    /**
     * Create an instance of {@link BackgroundType.Video }
     * 
     */
    public BackgroundType.Video createBackgroundTypeVideo() {
        return new BackgroundType.Video();
    }

    /**
     * Create an instance of {@link BackgroundImageType.Slideshow }
     * 
     */
    public BackgroundImageType.Slideshow createBackgroundImageTypeSlideshow() {
        return new BackgroundImageType.Slideshow();
    }

    /**
     * Create an instance of {@link NodeStyleType.Private }
     * 
     */
    public NodeStyleType.Private createNodeStyleTypePrivate() {
        return new NodeStyleType.Private();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CPEStyleSetType }{@code >}}
     *
    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/md/cpestyle/v1.0/cpestyle", name = "CPEStyleSet")
    public JAXBElement<CPEStyleSetType> createCPEStyleSet(CPEStyleSetType value) {
        return new JAXBElement<CPEStyleSetType>(_CPEStyleSet_QNAME, CPEStyleSetType.class, null, value);
    }
     */

}
